name: Build

on: [push]

jobs:
  windows:
    env:
      # Path to the solution file relative to the root of the project.
      SOLUTION_FILE_PATH: source/msvc/Star Ruler 2/Star Ruler 2.sln

      # Configuration type to build.
      # You can convert this to a build matrix if you need coverage of multiple configuration types.
      # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
      BUILD_CONFIGURATION: Non-Steam Release

    name: Windows build
    runs-on: windows-2016

    steps:
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: "msbuild /m \"/p:Configuration=${{env.BUILD_CONFIGURATION}}\" \"${{env.SOLUTION_FILE_PATH}}\""

    - name: Pack ZIP artifact
      run: "Compress-Archive -Path bin,credits.txt,\"Star Ruler 2.exe\",COPYING,sr2.ico -DestinationPath binaries.zip"
      shell: powershell

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: binaries.zip
        path: binaries.zip

  deploy:
    name: Deployment
    runs-on: ubuntu-latest

    needs:
    - windows

    steps:
    - uses: actions/checkout@v2

    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: binaries.zip

    - name: Update nightly Git tag
      run: git tag -f nightly && git push --force nightly

    - name: Update nightly release
      uses: WebFreak001/deploy-nightly@v1.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # automatically provided by github actions
      with:
        upload_url: https://uploads.github.com/repos/OpenSRProject/OpenStarRuler/releases/35747870/assets{?name,label}
        release_id: 35747870
        asset_path: ./binaries.zip
        asset_name: OpenStarRuler-binaries-windows-nightly-$$.zip
        asset_content_type: application/zip # required by GitHub API
        max_releases: 1
